version: '3.8'
services:
  api:
    build:
      context: ./
      target: dev
    environment:
      - PGUSER=postgres
      - PGHOST=postgres_container
      - PGDATABASE=postgres
      - PGPORT=5432 # node pg uses the same env vars as libpq to connect to postgres
      - PGPASSWORD=fortestingpurposesonly
      - JWT_KEY=fortestingpurposesonly
    ports:
      - "3000:3000"
    command: ${STARTUP_COMMAND:-}
    volumes:
      - "./src:/app/src"
  db:
    image: postgres:14
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fortestingpurposesonly
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432" # host:container
    # initialize the database with this file
    volumes:
      - ./src/database/database.sql:/docker-entrypoint-initdb.d/init.sql
